'use client'
import Link from 'next/link'
import { useState } from 'react'
import type { AdminProduct } from '@/lib/admin-products-db'
const labels = { public: 'на витрине', unlisted: 'по ссылке', hidden: 'скрыт' }
export default function AdminProductsList({ initialProducts }: { initialProducts: AdminProduct[] }) {
  const [products, setProducts] = useState(initialProducts); const [filter, setFilter] = useState<'all' | 'public' | 'unlisted' | 'hidden'>('all'); const shown = filter === 'all' ? products : products.filter((p) => p.visibility === filter)
  async function patch(id: number, change: object) { const response = await fetch(`/api/admin/products/${id}`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(change) }); if (response.ok) { const product = await response.json(); setProducts((all) => all.map((p) => p.id === id ? product : p)) } }
  return <><div className="admin-filters">{(['all', 'public', 'unlisted', 'hidden'] as const).map((item) => <button className={filter === item ? 'active' : ''} key={item} onClick={() => setFilter(item)}>{item === 'all' ? 'Все' : labels[item]}</button>)}</div><div className="admin-table">{shown.map((product) => <article className="admin-row" key={product.id}><div>{product.images[0] ? <img src={product.images.find((image) => image.isCover)?.filename ?? product.images[0].filename} alt="" /> : <div className="admin-placeholder" />}</div><div><strong>{product.name}</strong><small>{product.slug}</small></div><div><span className={`admin-badge ${product.visibility}`}>{labels[product.visibility]}</span><small>{product.inStock ? 'в наличии' : 'нет в наличии'}{product.isSaleActive ? ' · скидка активна' : ''}</small></div><div className="admin-row-actions"><select value={product.visibility} onChange={(e) => patch(product.id, { visibility: e.target.value })}>{Object.entries(labels).map(([key, label]) => <option key={key} value={key}>{label}</option>)}</select><label><input type="checkbox" checked={product.inStock} onChange={(e) => patch(product.id, { inStock: e.target.checked })} /> наличие</label><Link href={`/admin/products/${product.id}/edit`}>Изменить</Link></div></article>)}</div></>
}
