'use client'
import { useMemo, useState, type FormEvent } from 'react'
import { useRouter } from 'next/navigation'
import type { AdminProduct } from '@/lib/admin-products-db'
import { effectivePrice } from '@/lib/pricing'
import { slugify } from '@/lib/slug'
const rubles = (value: number) => String(value / 100).replace('.', ',')
const kopecks = (value: string) => Math.round(Number(value.replace(',', '.')) * 100)
const local = (value: string | null) => value ? new Date(value).toISOString().slice(0, 16) : ''
export default function AdminProductForm({ product }: { product?: AdminProduct }) {
  const router = useRouter(); const [name, setName] = useState(product?.name ?? ''); const [slug, setSlug] = useState(product?.slug ?? ''); const [price, setPrice] = useState(product ? rubles(product.priceKopecks) : ''); const [series, setSeries] = useState(product?.series ?? ''); const [subtitle, setSubtitle] = useState(product?.subtitle ?? ''); const [description, setDescription] = useState(product?.description ?? ''); const [scent, setScent] = useState(product?.scent.join(', ') ?? ''); const [visibility, setVisibility] = useState(product?.visibility ?? 'hidden'); const [inStock, setInStock] = useState(product?.inStock ?? true); const [salePrice, setSalePrice] = useState(product?.sale ? rubles(product.sale.priceKopecks) : ''); const [startsAt, setStartsAt] = useState(local(product?.sale?.startsAt ?? null)); const [endsAt, setEndsAt] = useState(local(product?.sale?.endsAt ?? null)); const [message, setMessage] = useState(''); const [images, setImages] = useState(product?.images ?? [])
  const preview = useMemo(() => effectivePrice({ priceKopecks: kopecks(price), salePriceKopecks: salePrice ? kopecks(salePrice) : null, saleStartsAt: startsAt ? new Date(startsAt).toISOString() : null, saleEndsAt: endsAt ? new Date(endsAt).toISOString() : null }, new Date()), [price, salePrice, startsAt, endsAt])
  async function submit(event: FormEvent) { event.preventDefault(); const sale = salePrice ? { priceKopecks: kopecks(salePrice), startsAt: startsAt ? new Date(startsAt).toISOString() : null, endsAt: endsAt ? new Date(endsAt).toISOString() : null } : null; const body = { name, slug, priceKopecks: kopecks(price), series: series || null, subtitle: subtitle || null, description: description || null, scent: scent.split(',').map((x) => x.trim()).filter(Boolean), visibility, inStock, sale }; const response = await fetch(product ? `/api/admin/products/${product.id}` : '/api/admin/products', { method: product ? 'PATCH' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(body) }); if (response.ok) { const saved = await response.json(); router.replace(`/admin/products/${saved.id}/edit`); router.refresh() } else { const error = await response.json().catch(() => null); setMessage(error?.error?.messages?.join('. ') ?? 'Не удалось сохранить') } }
  async function upload(files: FileList | null) { if (!product || !files?.length) return; const data = new FormData(); data.set('productId', String(product.id)); [...files].forEach((file) => data.append('files', file)); const response = await fetch('/api/upload', { method: 'POST', body: data }); if (response.ok) { const result = await response.json(); setImages((old) => [...old, ...result.images]) } else setMessage((await response.json()).error?.messages?.[0] ?? 'Не удалось загрузить фото') }
  async function removeImage(id: number) { if (!product) return; const response = await fetch(`/api/admin/products/${product.id}/images/${id}`, { method: 'DELETE' }); if (response.ok) { setImages((old) => old.filter((image) => image.id !== id)); router.refresh() } }
  async function cover(id: number) { if (!product) return; const response = await fetch(`/api/admin/products/${product.id}/images`, { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ orderedImageIds: images.map((image) => image.id), coverImageId: id }) }); if (response.ok) setImages((old) => old.map((image) => ({ ...image, isCover: image.id === id }))) }
  return <form className="admin-form" onSubmit={submit}><div className="admin-form-grid"><label>Название<input required maxLength={200} value={name} onChange={(e) => setName(e.target.value)} /></label><label>Slug<div className="admin-inline"><input required value={slug} onChange={(e) => setSlug(e.target.value)} /><button type="button" onClick={() => setSlug(slugify(name))}>из названия</button></div></label><label>Цена, ₽<input required inputMode="decimal" value={price} onChange={(e) => setPrice(e.target.value)} /></label><label>Серия<input value={series} onChange={(e) => setSeries(e.target.value)} /></label><label>Подзаголовок<input value={subtitle} onChange={(e) => setSubtitle(e.target.value)} /></label><label>Ароматы через запятую<input value={scent} onChange={(e) => setScent(e.target.value)} /></label><label className="admin-wide">Описание<textarea value={description} onChange={(e) => setDescription(e.target.value)} /></label></div><fieldset><legend>Витрина</legend>{([['public', 'На витрине'], ['unlisted', 'Только по ссылке'], ['hidden', 'Скрыт']] as const).map(([value, text]) => <label className="admin-radio" key={value}><input type="radio" checked={visibility === value} value={value} onChange={() => setVisibility(value)} />{text}</label>)}<label className="admin-radio"><input type="checkbox" checked={inStock} onChange={(e) => setInStock(e.target.checked)} /> В наличии</label></fieldset><fieldset><legend>Скидка</legend><div className="admin-form-grid"><label>Цена скидки, ₽<input inputMode="decimal" value={salePrice} onChange={(e) => setSalePrice(e.target.value)} /></label><label>Начало <small>(локальное время)</small><input type="datetime-local" value={startsAt} onChange={(e) => setStartsAt(e.target.value)} /></label><label>Окончание <small>(локальное время)</small><input type="datetime-local" value={endsAt} onChange={(e) => setEndsAt(e.target.value)} /></label></div><p>Сейчас: {preview.kopecks / 100} ₽ {preview.isOnSale ? '(скидка активна)' : '(обычная цена)'}</p><button type="button" onClick={() => { setSalePrice(''); setStartsAt(''); setEndsAt('') }}>Убрать скидку</button></fieldset>{product && <fieldset><legend>Фото</legend><input type="file" accept="image/jpeg,image/png,image/webp" multiple onChange={(e) => upload(e.target.files)} /><div className="admin-images">{images.map((image) => <div key={image.id}><img src={image.filename} alt="" /><button type="button" onClick={() => cover(image.id)}>{image.isCover ? 'Обложка' : 'Сделать обложкой'}</button><button type="button" onClick={() => removeImage(image.id)}>Удалить</button></div>)}</div></fieldset>}{message && <p className="admin-error">{message}</p>}<button className="admin-button">Сохранить</button></form>
}
