'use client'

import { useState } from 'react'
import type { TelegramSettings } from '@/lib/telegram-settings'

export default function TelegramSettingsForm({ initial }: { initial: TelegramSettings }) {
  const [saved, setSaved] = useState(initial); const [enabled, setEnabled] = useState(initial.enabled); const [chatId, setChatId] = useState(initial.chatId ?? ''); const [token, setToken] = useState(''); const [error, setError] = useState(''); const [busy, setBusy] = useState(false)
  async function save() { setBusy(true); setError(''); const response = await fetch('/api/admin/settings/notifications', { method: 'PATCH', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ enabled, ...(chatId.trim() ? { chatId } : {}), ...(token ? { botToken: token } : {}) }) }); const body = await response.json().catch(() => null); setBusy(false); if (!response.ok) { setError(body?.error?.messages?.[0] ?? 'Не удалось сохранить настройку'); return }; setSaved(body); setEnabled(body.enabled); setChatId(body.chatId ?? ''); setToken('') }
  async function clear() { if (!confirm('Удалить токен и отключить уведомления? Неотправленные сообщения будут отменены.')) return; setBusy(true); setError(''); const response = await fetch('/api/admin/settings/notifications', { method: 'DELETE', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: true }) }); setBusy(false); if (!response.ok) { setError('Не удалось удалить токен'); return }; const next = { enabled: false, chatId: null, configured: false, tokenLast4: null, updatedAt: new Date().toISOString(), lastDeliveryError: null, lastDeliveryErrorAt: null }; setSaved(next); setEnabled(false); setChatId(''); setToken('') }
  return <div className="admin-settings"><p>Сообщения приходят только о событиях заказа. Бот не принимает команды и не меняет данные магазина.</p>{error && <p className="admin-error">{error}</p>}<label><input type="checkbox" checked={enabled} onChange={(event) => setEnabled(event.target.checked)} /> Включить уведомления</label><label className="checkout-field"><span>Токен Telegram-бота</span><input type="password" autoComplete="new-password" value={token} onChange={(event) => setToken(event.target.value)} placeholder={saved.configured ? 'Оставьте пустым, чтобы сохранить текущий' : '123456:ABC…'} /></label><label className="checkout-field"><span>ID чата</span><input value={chatId} onChange={(event) => setChatId(event.target.value)} placeholder="-1001234567890" /></label>{saved.configured && <p>Текущий токен: настроен (…{saved.tokenLast4})</p>}{saved.lastDeliveryError && <p className="admin-error">Последняя ошибка доставки: {saved.lastDeliveryError}</p>}<button className="admin-button" disabled={busy} onClick={save}>{busy ? 'Сохраняем…' : 'Сохранить'}</button>{saved.configured && <button className="admin-button" disabled={busy} onClick={clear}>Отключить и удалить токен</button>}</div>
}
